#NetCDF to CSV

#add the path to the NetCDF file generated by XBeach at "your-file-in"

#select a location for the converter to place a CSV at "your-file-out"

#this process requires the XArray package, which can be installed via pip or conda and then imported

#this script was obtained from:
#https://help.marine.copernicus.eu/en/articles/4839794-how-to-convert-netcdf-to-csv

import xarray as xr

#open dataset
XBeach_SRC = xr.open_dataset("your-file-in.nc")

#convert dataset to CSV dataframe
XBeach_SRC.to_dataframe().to_csv("your-file-out.csv")